// Mock data for Senegalese Marketplace

export const translations = {
  fr: {
    nav: {
      home: 'Accueil',
      products: 'Produits',
      services: 'Services',
      messages: 'Messages',
      profile: 'Profil',
      login: 'Connexion',
      signup: 'Inscription',
      logout: 'Déconnexion',
      postProduct: 'Vendre un produit',
      postService: 'Proposer un service'
    },
    hero: {
      title: 'Achetez, Vendez, Échangez au Sénégal',
      subtitle: 'La marketplace qui réunit produits d\'occasion et services de proximité',
      searchPlaceholder: 'Rechercher un produit ou service...',
      searchButton: 'Rechercher'
    },
    categories: {
      productsTitle: 'Catégories Produits',
      servicesTitle: 'Catégories Services',
      // --- Produits existants ---
      tech: 'Téléphones & Informatique',
      electronics: 'Électronique & Informatique',
      fashion: 'Mode & Vêtements',
      beauty_products: 'Cosmétiques & Coiffure',
      thrift: 'Friperie (Seconde main)',
      vehicles: 'Véhicules & Motos',
      home: 'Maison & Électroménager',
      kids: 'Enfants & Bébés',
      real_estate: 'Immobilier (Locations/Ventes)',
      // --- Nouveaux produits : agro, élevage, alimentation ---
      agriculture: 'Agriculture & Maraîchage',
      livestock: 'Élevage & Bétail',
      fishing: 'Pêche & Produits de mer',
      food_local: 'Alimentation & Produits locaux',
      crafts: 'Artisanat & Décoration',
      tools: 'Outillage & Équipements',
      sports: 'Sport & Loisirs',
      books: 'Livres, Jeux & Musique',
      // --- Services existants ---
      cleaning: 'Ménage & Nettoyage',
      handyman: 'Bricolage',
      delivery: 'Livraison locale',
      beauty: 'Beauté & Coiffure',
      tutoring: 'Cours particuliers',
      moving: 'Déménagement',
      catering: 'Restauration & Traiteur',
      repairs: 'Réparations diverses',
      lessons: 'Cours & Formations',
      // --- Nouveaux services sénégalais ---
      gp_shipping: 'GP – Envoi de colis par avion',
      plumbing: 'Plomberie',
      masonry: 'Maçonnerie & BTP',
      electricity: 'Électricité',
      painting: 'Peinture & Décoration intérieure',
      welding: 'Soudure & Ferronnerie',
      mechanics: 'Mécanique auto & moto',
      tailoring: 'Couture & Tailleur',
      hair_braiding: 'Tressage & Coiffure à domicile',
      security: 'Gardiennage & Sécurité',
      farming: 'Agriculture & Jardinage',
      it_services: 'Informatique & Dépannage',
      events: 'Événementiel, DJ & Photo',
      transport: 'Transport & VTC',
      childcare: 'Garde d\'enfants & Baby-sitting',
      laundry: 'Laverie & Repassage',
      cooking: 'Cuisine à domicile',
      health: 'Santé & Bien-être',
      legal: 'Conseil juridique & Administratif'
    },
    auth: {
      loginTitle: 'Connexion',
      signupTitle: 'Inscription',
      email: 'Email',
      password: 'Mot de passe',
      confirmPassword: 'Confirmer le mot de passe',
      firstName: 'Prénom',
      lastName: 'Nom',
      phone: 'Téléphone',
      location: 'Ville',
      loginButton: 'Se connecter',
      signupButton: 'S\'inscrire',
      noAccount: 'Pas de compte ?',
      hasAccount: 'Déjà un compte ?'
    },
    product: {
      condition: 'État',
      price: 'Prix',
      location: 'Localisation',
      seller: 'Vendeur',
      description: 'Description',
      contact: 'Contacter',
      buy: 'Acheter',
      new: 'Neuf',
      likeNew: 'Comme neuf',
      good: 'Bon état',
      fair: 'État correct',
      reviews: 'Avis'
    },
    service: {
      rate: 'Tarif',
      availability: 'Disponibilité',
      provider: 'Prestataire',
      book: 'Réserver',
      perHour: '/heure',
      perDay: '/jour',
      fixed: 'Prix fixe',
      perProject: '/projet'
    },
    payment: {
      title: 'Paiement',
      wave: 'Wave',
      orangeMoney: 'Orange Money',
      total: 'Total',
      confirm: 'Confirmer le paiement'
    }
  },
  wo: {
    nav: {
      home: 'Kër',
      products: 'Alal',
      services: 'Liggéey',
      messages: 'Bataaxal',
      profile: 'Profil',
      login: 'Dugg',
      signup: 'Bind',
      logout: 'Génn',
      postProduct: 'Jaay alal',
      postService: 'Jaay liggéey'
    },
    hero: {
      title: 'Jënd, Jaay, Weccee ci Sénégal',
      subtitle: 'Marketplace bi tattalee alal yu yore ak liggéey yu jëkk',
      searchPlaceholder: 'Seet alal walla liggéey...',
      searchButton: 'Seet'
    },
    categories: {
      productsTitle: 'Kawu Alal',
      servicesTitle: 'Kawu Liggéey',
      // --- Produits existants ---
      tech: 'Telefon & Ordinateur',
      electronics: 'Électronique & Informatique',
      fashion: 'Yere ak Njul',
      beauty_products: 'Rafetaay ak Tès',
      thrift: 'Fugëjaay',
      vehicles: 'Auto ak Moto',
      home: 'Kër ak Électroménager',
      kids: 'Xale ak Bébé',
      real_estate: 'Kër ak Suuf (Jaay/Luwe)',
      // --- Nouveaux produits : agro, élevage, alimentation ---
      agriculture: 'Liggéey àll ak Légume',
      livestock: 'Ségé ak Xar',
      fishing: 'Jën ak Mbëkk',
      food_local: 'Lekk ak Ceep yu Senegaal',
      crafts: 'Laaj ak Dëkk-dëkk',
      tools: 'Jumtukaay ak Maccudo',
      sports: 'Sport ak Fàww-fàww',
      books: 'Téere, Jëkkër ak Gàmmu',
      // --- Services existants ---
      cleaning: 'Sedd ak Ceebu',
      handyman: 'Brikolaj',
      delivery: 'Yoon ci dëkk',
      beauty: 'Rafet & Tès',
      tutoring: 'Jàng bu boppam',
      moving: 'Déménaj',
      catering: 'Toggu & Lekk',
      repairs: 'Sàcc yu ndaw',
      lessons: 'Jàng ak Fàtte',
      // --- Nouveaux services sénégalais ---
      gp_shipping: 'GP – Yónn colis ci avion',
      plumbing: 'Plomberie',
      masonry: 'Maçonnerie ak BTP',
      electricity: 'Électricité',
      painting: 'Peinture ak Rafetaaykër',
      welding: 'Soudure ak Fer',
      mechanics: 'Mécanicien auto ak moto',
      tailoring: 'Tailleur ak Couture',
      hair_braiding: 'Tressage ak Coiffure ci kër',
      security: 'Gardien ak Sécurité',
      farming: 'Liggéey àll & Jardinage',
      it_services: 'Ordinateur ak Depanaj',
      events: 'Événement, DJ ak Photo',
      transport: 'Yoon ak VTC',
      childcare: 'Garde xale ak Baby-sitting',
      laundry: 'Ngënnde ak Tëk yere',
      cooking: 'Toggu ci kër',
      health: 'Yaram ak Dëgënte',
      legal: 'Serin ak Administratif'
    },
    auth: {
      loginTitle: 'Dugg',
      signupTitle: 'Bind',
      email: 'Email',
      password: 'Mot de passe',
      confirmPassword: 'Nettali mot de passe',
      firstName: 'Tur',
      lastName: 'Sant',
      phone: 'Telefon',
      location: 'Dëkk',
      loginButton: 'Dugg',
      signupButton: 'Bind',
      noAccount: 'Amoul compte ?',
      hasAccount: 'Am na compte ?'
    },
    product: {
      condition: 'Njëg',
      price: 'Ñaari xaalis',
      location: 'Fan',
      seller: 'Kijaay',
      description: 'Xamlekat',
      contact: 'Waxtaan',
      buy: 'Jënd',
      new: 'Bees',
      likeNew: 'Ni bees',
      good: 'Baax',
      fair: 'Ndañul bañ',
      reviews: 'Luyxassare'
    },
    service: {
      rate: 'Mbir',
      availability: 'Mënoul',
      provider: 'Liggéeykat',
      book: 'Retenir',
      perHour: '/waxtu',
      perDay: '/bés',
      fixed: 'Mbir tepp',
      perProject: '/projet'
    },
    payment: {
      title: 'Fey',
      wave: 'Wave',
      orangeMoney: 'Orange Money',
      total: 'Lépp',
      confirm: 'Nettali fey'
    }
  }
};

export const products = [
  {
    id: '1',
    title: 'iPhone 12 Pro - Comme neuf',
    titleWo: 'iPhone 12 Pro - Ni bees',
    price: 275000,
    category: 'tech',
    condition: 'likeNew',
    location: 'Dakar, Plateau',
    images: ['https://images.unsplash.com/photo-1591337676887-a217a6970a8a?w=800', 'https://images.unsplash.com/photo-1603791239531-10748d0ba08d?w=800'],
    description: 'iPhone 12 Pro 128GB en excellent état, avec boîte et accessoires d\'origine. Batterie à 92%. Aucune rayure.',
    descriptionWo: 'iPhone 12 Pro 128GB, njëg baaxul. Am na boîte ak accessoires. Batterie 92%.',
    seller: { id: 'u1', name: 'Mamadou Diop', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mamadou', rating: 4.8, reviewCount: 24, sellerPhone: '+221770000001' },
    createdAt: '2025-01-10'
  },
  {
    id: '2',
    title: 'Robe africaine traditionnelle en wax',
    titleWo: 'Njul bu afrik bu jëkk ci wax',
    price: 15000,
    category: 'fashion',
    condition: 'good',
    location: 'Dakar, Médina',
    images: ['https://images.pexels.com/photos/2170387/pexels-photo-2170387.jpeg?w=800'],
    description: 'Belle robe traditionnelle en wax, taille M. Portée 2 fois seulement.',
    descriptionWo: 'Njul bu rafet ci wax, taille M. Yere ñaar bés rekk.',
    seller: { id: 'u2', name: 'Aïssatou Fall', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aissatou', rating: 4.9, reviewCount: 31, sellerPhone: '+221770000002' },
    createdAt: '2025-01-12'
  },
  {
    id: '3',
    title: 'Canapé 3 places - État neuf',
    titleWo: 'Kanape 3 places - Bees',
    price: 120000,
    category: 'home',
    condition: 'likeNew',
    location: 'Dakar, Almadies',
    images: ['https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?w=800'],
    description: 'Canapé moderne 3 places en très bon état. Couleur gris clair, très confortable.',
    descriptionWo: 'Kanape bees 3 places. Mëlni gri, rafet na.',
    seller: { id: 'u3', name: 'Ousmane Seck', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ousmane', rating: 4.7, reviewCount: 18, sellerPhone: '+221770000003' },
    createdAt: '2025-01-08'
  },
  {
    id: '4',
    title: 'Laptop HP Pavilion i5',
    titleWo: 'Ordinateur HP Pavilion i5',
    price: 180000,
    category: 'tech',
    condition: 'good',
    location: 'Thiès',
    images: ['https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg?w=800'],
    description: 'HP Pavilion i5, 8GB RAM, 256GB SSD. Parfait pour études et bureau. Windows 11.',
    descriptionWo: 'HP Pavilion i5, 8GB RAM, 256GB SSD. Baax na ci jàng ak liggéey.',
    seller: { id: 'u4', name: 'Fatou Sarr', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatou', rating: 4.6, reviewCount: 15, sellerPhone: '+221770000004' },
    createdAt: '2025-01-11'
  },
  {
    id: '5',
    title: 'Poussette bébé + siège auto',
    titleWo: 'Poussette bebé + siège auto',
    price: 45000,
    category: 'kids',
    condition: 'good',
    location: 'Dakar, Sicap',
    images: ['https://images.pexels.com/photos/6849259/pexels-photo-6849259.jpeg?w=800'],
    description: 'Ensemble poussette et siège auto pour bébé. Bon état, propre.',
    descriptionWo: 'Poussette ak siège auto bu bebé. Njëg baaxul, sedd.',
    seller: { id: 'u5', name: 'Khady Ndiaye', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Khady', rating: 5.0, reviewCount: 8, sellerPhone: '+221770000005' },
    createdAt: '2025-01-13'
  }
];

export const services = [
  {
    id: 's1',
    title: 'Service de ménage professionnel',
    titleWo: 'Liggéey sedd bu professionnel',
    category: 'cleaning',
    rate: 5000,
    rateType: 'perHour',
    location: 'Dakar',
    image: 'https://images.pexels.com/photos/48889/cleaning-washing-cleanup-the-ilo-48889.jpeg?w=800',
    description: 'Service de ménage complet pour maisons et appartements. Produits inclus.',
    descriptionWo: 'Liggéey sedd bu baax ci kër. Produit am.',
    provider: { id: 'p1', name: 'Aminata Cissé', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aminata', rating: 4.9, reviewCount: 47, completedJobs: 132, providerPhone: '+221770000006' },
    availability: 'Disponible du lundi au samedi',
    createdAt: '2025-01-05'
  },
  {
    id: 's2',
    title: 'Bricolage & Réparations',
    titleWo: 'Brikolaj & Réparations',
    category: 'handyman',
    rate: 15000,
    rateType: 'perDay',
    location: 'Dakar, Rufisque',
    image: 'https://images.pexels.com/photos/1249611/pexels-photo-1249611.jpeg?w=800',
    description: 'Tous travaux de bricolage : plomberie, électricité, menuiserie, peinture. 15 ans d\'expérience.',
    descriptionWo: 'Liggéey brikolaj yépp : plomberie, électricité, menuiserie. 15 at ci liggéey.',
    provider: { id: 'p2', name: 'Ibrahima Sy', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ibrahima', rating: 4.8, reviewCount: 63, completedJobs: 210, providerPhone: '+221770000007' },
    availability: 'Disponible tous les jours',
    createdAt: '2025-01-07'
  },
  {
    id: 's3',
    title: 'Livraison rapide Dakar',
    titleWo: 'Yoon gaaw ci Dakar',
    category: 'delivery',
    rate: 2000,
    rateType: 'fixed',
    location: 'Dakar',
    image: 'https://images.pexels.com/photos/4391478/pexels-photo-4391478.jpeg?w=800',
    description: 'Service de livraison rapide dans tout Dakar. Colis, courses, documents.',
    descriptionWo: 'Yoon gaaw ci Dakar lépp. Colis, courses, documents.',
    provider: { id: 'p3', name: 'Moussa Diouf', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Moussa', rating: 4.7, reviewCount: 89, completedJobs: 345, providerPhone: '+221770000008' },
    availability: '24/7',
    createdAt: '2025-01-09'
  },
  {
    id: 's4',
    title: 'Tressage & Coiffure à domicile',
    titleWo: 'Tressage ak Coiffure ci kër',
    category: 'hair_braiding',
    rate: 8000,
    rateType: 'fixed',
    location: 'Dakar',
    image: 'https://images.pexels.com/photos/3865717/pexels-photo-3865717.jpeg?w=800',
    description: 'Coiffure à domicile : tresses, nattes, tissage, lissage. Produits de qualité.',
    descriptionWo: 'Coiffure ci kër : tresses, nattes, tissage, lissage.',
    provider: { id: 'p4', name: 'Mariama Touré', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mariama', rating: 5.0, reviewCount: 52, completedJobs: 98, providerPhone: '+221770000009' },
    availability: 'Sur rendez-vous',
    createdAt: '2025-01-06'
  },
  {
    id: 's5',
    title: 'Cours particuliers Maths & Physique',
    titleWo: 'Jàng bu boppam Maths & Physique',
    category: 'tutoring',
    rate: 7500,
    rateType: 'perHour',
    location: 'Dakar',
    image: 'https://images.pexels.com/photos/3861966/pexels-photo-3861966.jpeg?w=800',
    description: 'Professeur certifié donne cours particuliers Maths et Physique. Collège et Lycée.',
    descriptionWo: 'Prof certifié. Cours Maths ak Physique. Collège ak Lycée.',
    provider: { id: 'p5', name: 'Cheikh Diallo', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Cheikh', rating: 4.9, reviewCount: 34, completedJobs: 67, providerPhone: '+221770000010' },
    availability: 'Lundi, Mercredi, Samedi',
    createdAt: '2025-01-04'
  },
  {
    id: 's6',
    title: 'Déménagement & Transport',
    titleWo: 'Déménaj & Yoon',
    category: 'moving',
    rate: 35000,
    rateType: 'fixed',
    location: 'Dakar, Thiès',
    image: 'https://images.pexels.com/photos/4569340/pexels-photo-4569340.jpeg?w=800',
    description: 'Service de déménagement complet avec camion et équipe. Dakar et environs.',
    descriptionWo: 'Liggéey déménagement ak camion ak équipe. Dakar ak jàppale.',
    provider: { id: 'p6', name: 'Abdoulaye Ba', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Abdoulaye', rating: 4.6, reviewCount: 28, completedJobs: 76, providerPhone: '+221770000011' },
    availability: 'Sur demande',
    createdAt: '2025-01-10'
  }
];

export const reviews = [
  {
    id: 'r1',
    userId: 'u7',
    userName: 'Seydou Kane',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Seydou',
    rating: 5,
    comment: 'Excellent service, très professionnel. Je recommande vivement !',
    commentWo: 'Liggéey bu baax, professionnel na lool. Waar nga !',
    date: '2025-01-12'
  },
  {
    id: 'r2',
    userId: 'u8',
    userName: 'Awa Diagne',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Awa',
    rating: 4,
    comment: 'Très satisfaite, produit conforme à la description.',
    commentWo: 'Kontaan na, alal ni xamlekat.',
    date: '2025-01-11'
  },
  {
    id: 'r3',
    userId: 'u9',
    userName: 'Modou Mbaye',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Modou',
    rating: 5,
    comment: 'Service rapide et efficace. Très bon rapport qualité/prix.',
    commentWo: 'Liggéey gaaw te baax. Mbir baax.',
    date: '2025-01-09'
  }
];

export const categoryIcons = {
  fashion: 'Shirt',
  electronics: 'Laptop',
  tech: 'Smartphone',
  home: 'Home',
  kids: 'Baby',
  vehicles: 'Car',
  thrift: 'Tag',
  beauty_products: 'Sparkles',
  real_estate: 'Building',
  agriculture: 'Leaf',
  livestock: 'Beef',
  fishing: 'Fish',
  food_local: 'ShoppingBasket',
  crafts: 'Palette',
  tools: 'Wrench',
  sports: 'Trophy',
  books: 'BookOpen',
  cleaning: 'Sparkles',
  handyman: 'Hammer',
  delivery: 'Truck',
  beauty: 'Scissors',
  hair_braiding: 'Scissors',
  tutoring: 'BookOpen',
  moving: 'Package',
  gp_shipping: 'Plane',
  plumbing: 'Droplets',
  masonry: 'Building2',
  electricity: 'Zap',
  painting: 'Paintbrush',
  welding: 'Flame',
  mechanics: 'Car',
  tailoring: 'Scissors',
  security: 'Shield',
  farming: 'Leaf',
  it_services: 'Monitor',
  events: 'Music',
  transport: 'Car',
  childcare: 'Baby',
  laundry: 'Wind',
  cooking: 'UtensilsCrossed',
  health: 'Heart',
  legal: 'Scale'
};
